version: '3.4'

services:
  e8ay.user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8100:80"
    depends_on:
      - e8ay.mongo
      - e8ay.item.api

  e8ay.item.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8200:80"
    depends_on:
      - e8ay.mongo

  e8ay.bid.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8300:80"
    depends_on:
      - e8ay.mongo
      - e8ay.item.api

  e8ay.web:
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - e8ay.mongo
      - e8ay.user.api
      - e8ay.item.api
      - e8ay.bid.api
      