version: '3.5'

services:

  e8ay-web-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CI=true
    command: npm test